name: pets
description: A new Flutter application.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.33+33

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  # device_preview: ^0.5.5
  permission_handler: ^8.1.4+2
  # http: ^0.12.2
  shared_preferences: null
  url_launcher: ^6.0.3
  firebase_core: ^1.5.0
  firebase_messaging: ^10.0.5
  flutter_local_notifications: ^8.1.1+1
  # searchable_dropdown: ^1.1.3
  carousel_slider: ^4.0.0
  sms_autofill: ^2.0.0
  flutter_calendar_carousel: ^2.0.1
  firebase_dynamic_links: ^2.0.8
  toast:
  flutter_country_picker: ^0.1.6
  dotted_border: ^2.0.0+1
  provider: ^5.0.0
  qr_flutter: ^4.0.0
  flutter_barcode_scanner: ^2.0.0
  platform_device_id: ^1.0.1
  share: ^2.0.1
  timeline_tile: ^2.0.0
  package_info: ^2.0.0
  feature_discovery: ^0.14.0
  flutter_slidable: ^0.6.0
  highlighter_coachmark: ^0.0.3
  in_app_review: ^2.0.2
  firebase_analytics: ^8.3.0
  contacts_service: ^0.6.1
  animations: ^2.0.0
  syncfusion_flutter_sliders: ^19.2.56
  table_calendar: ^3.0.0
  fl_chart: ^0.36.1
  flutter_native_timezone: ^2.0.0
  social_share: ^2.1.1
  flutter_offline: ^2.0.0

  #Story Related Plugins
  # aws_s3: ^0.1.1+hotfix.5
  mime: ^1.0.0
  camera: ^0.8.1+5
  flutter_colorpicker: ^0.5.0
  image_editor: ^1.0.0
  extended_image: ^4.1.0
  video_player: ^2.1.14
  image: ^3.0.2
  file_picker: ^4.0.0
  uuid: ^3.0.4
  google_fonts: ^2.1.0
  image_picker: ^0.8.3+3
  video_trimmer: ^0.5.4
  flutter_form_builder: ^6.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  # intl: 0.16.0
  # plugin_platform_interface: 1.0.2 
  # 
  # quiver: ^3.0.0
  # http: ^0.12.2
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/gif/
    - assets/sounds/
    - assets/svg/
    - assets/stickers/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

